### ISSUE TITLE
[Guide - Tracking Issue] Intro to Parachain Development Guide

### ISSUE THREAD

**Issue by CrackTheCode016** [w3f/w3f-education#107]
This guide will help you with the steps needed to connect a basic parachain to a relay chain.  Eventually, this should also guide in relation to cross-consensus communication, best practices, and more.

> Note: This will most likely changed, what's laid out here is just preliminary or "intro" material.

### Section 1 - Parachain Architecture Overview

- [ ] Network Components
- [ ] Relay Chain
- [ ] Parachain

### Section 2 - Dependency Installation

- [ ] Installing local binaries
- [ ] Installing parachain-template installation
- [ ] Running the relay and parachain

### Section 3 - Creating & Registering Parachain

- [ ] Customizing your parachain with FRAME
- [ ] Creating a parathread
- [ ] Prepare and hold parachain auction

### Section 4 - Moving Forward

- [ ] Road to Production
- [ ] Substrate Builders Program

**Comment by CrackTheCode016** [comment]
It's possible this will be seperated into two seperate sub-guides: 

- An "easy" guide with Zombienet, which I think should be emphasized more
- A more "advanced" guide that emphasizes more usage of tools like `try-runtime-cli`, `build-spec`, etc.
