### ISSUE TITLE
Introduction to Rust / Rust for Beginners MOOC

### ISSUE THREAD

**Issue by CrackTheCode016** [w3f/w3f-education#38]
As part of the effort to bootstrap this repo with a slew of educational content, here is an issue to address and track anything related to the introduction to Rust MOOC.  It will mostly introduce core concepts of Rust that are deemed relevant, as well as Wasm.

Keep in mind this is purely to provide a good introduction with hands-on examples. Over time, more content can be provided - but this serves as the baseline for learning Rust in the context of web3!

The following modules are planned/being implemented: 

1. [x] Why Learn Rust (Intro to Wasm)? -> PR #37 
2. [x] Installing & Setting up a Rust Development Environment -> PR #40 
3. [x] Rust 101 - The Basics -> PR #42 
4. [x] Intro to Intermediate Rust: Ownership, Borrowing, & Slices -> PR #44 
5. [x] Intro to Intermediate Rust: Enums & Matching Patterns -> PR #45 
6. [x] Intro to Intermediate Rust: Data Structs & Collections -> PR #46 
7. [x] Intro to Advanced Rust: Traits, Generics, & Lifetimes -> PR #47 
8. [x] Intro to Advanced Rust: Iterators & Closures -> PR #49 
9. [x] Learning Cargo, Rust’s Package Management System, Basic Testing -> PR #50

**Comment by NukeManDan** [comment]
This will surely be something we want to drive as a start for the polkadot blockchain academy (PBA) as a starter resource!

I am curious if this will gear anyone completing it to pass the exam, including optional and advanced aspects? I know it is not yet open to the general public, but some of it will be shortly: an open moderately hard portion to apply must be completed, and a much harder closed segment to those who do well in the exam will be required to do as best they can on, likely to be more advanced than the scope of this rust MOOC you are crafting. 

Based on your experience with the last rust exam, what level of the optional harder portions will this mooc prepare one for, if any?

**Comment by NukeManDan** [comment]
Also curiius about why this is needed over existing rust learner content. Is there some study of the landscape of materials that exists and where this mooc needs to craft otherwise unavailable materials? I am sure there are generally some key things that do not have good open access materials, but have yet to see a rigorous assessment done by web3 or PBA or Parutt for that matter (as we want to suggest the best resources we can as well!)

**Comment by CrackTheCode016** [comment]
@NukeManDan *really* good questions, I had some of the same when starting to develop this course.  For starters, the original intention of this course is to provide an introduction to Rust in a way that accomplishes two goals (as of right now): 

1. Provide an introduction to Rust in a way that doesn't completely overwhelm the learner with content, but rather moreso exposes them to necessary concepts through hands-on examples. From there, learning something like Substrate won't be *as* high barrier as it was before.

2. Fills a few knowledge gaps in Rust learner resources - something that is easy to follow, very accessible, interactive, and piques interest into more of why Rust is currently pretty imperative for blockchain.  It should eventually provide a very natural progression into FRAME & Substrate, and learning core architectural concepts around it.

Another (eventual) goal is to provide more resources around Wasm, specifically Substrate's/Polkadot's utilization of it.  

> I am curious if this will gear anyone completing it to pass the exam, including optional and advanced aspects?

As it is based partially on the Rust book's content, then I would say on a *basic* level it would definitely help with something like this exam.  Regarding optional/advanced aspects, I don't think it would go in-depth enough to aid in it at this point completely.  

> Based on your experience with the last rust exam, what level of the optional harder portions will this mooc prepare one for, if any?

It might help with a couple of sections, but mostly just with familiarity with a *little* syntax (namely, when it comes to generics / associated type usage).  Although arguably, due to both more introductory + lack of super extensive examples, it will still be a challenge if the student is not used to Rust in the first place.

There are also a couple of concepts **not** covered in this mooc that are in the exam ;)

>  Also curious about why this is needed over existing rust learner content. 

The currently available Rust content is quite adequate, but it's worth noting that the way Substrate, for example, uses Rust is definitely different than normal in some regards.   Within this mooc, I definitely hope to hint at the usage of some of those patterns so that these choices make sense when they come across them in the wild.

I would be interested in doing a more academic assessment of *why* this could be better as a general learning path.  I have a few reasons, mostly to do with learning flow and interactability.  It will provide a lot more cohesion into not only learning the language, but also where to go from there.
