### ISSUE TITLE
Intro to Substrate MOOC (Tracking Issue)

### ISSUE THREAD

**Issue by CrackTheCode016** [w3f/w3f-education#60]
As the second stage of drafting educational content, this next course will focus on an **Intro to building blockchains with Substrate**.  It will be building on top of previous Rust knowledge that exists in this repo.

The following modules are initially planned but are subject to be adjusted or changed over time: 

- [x] What is Substrate and Why Learn It? -> PR #95 
- [x] Substrate 101 - Overview -> PR #96 
- [x] Installing Dependencies & Node Template -> PR #97 
- [x] Building a Custom FRAME Pallet: Intro -> PR #98  
- [x] Building a Custom FRAME Pallet: Making our pallet actionable -> PR #101 
- [x] Building a Custom FRAME Pallet: Deploying & Testing -> PR #102 
- [x] Building a Custom FRAME Pallet: Pallet & FRAME best practices -> PR #103 
- [x] Substrate Deepdive - Origins, Weights, and Benchmarking -> PR #105

**Comment by CrackTheCode016** [comment]
Extraneous action items to add (but not super priority): 

- [ ] Glossary
- [ ] Introduction to capstone project

**Comment by CrackTheCode016** [comment]
Another thought - it would be nice to create a component that is more catered to a course like this.. just initial thoughts:

- A component that automatically create a "path" (both visual and through links) of content that depends on one another, would help in defining various of interest.
   - Example: On events and errors page, you should've completed x, y, and z objectives and concepts.
- Component to track progress of various concept.s

Of course, this could be argued that docusaurus is not the best tool to use for this :) but we shall see.

**Comment by CrackTheCode016** [comment]
Cross-referencing from the wiki to here (and vice-versa) would be beneficial as a sidenote.  

This PR is relevant, and should see the first sight of this:  https://github.com/w3f/polkadot-wiki/pull/4810

**Comment by CrackTheCode016** [comment]
Initial course content has been merged 🎉
